# 输出修改文件清单
print("### 修改文件清单")
print("1. `d:\\MyTradingBot\\ui_legacy.py` - 删除了覆盖主题的白色背景CSS代码")
print()

# 输出diff
print("### git diff")
print('```diff')
print('--- ui_legacy.py.old')
print('+++ ui_legacy.py.new')
print('@@ -227,13 +227,5 @@')
print(' def render_dashboard(view_model, actions):')
print('     """渲染主仪表盘"""')
print('-     # 设置页面样式')
print('-     st.markdown("""')
print('-     <style>')
print('-         .stApp { background-color: #f7f7f9; font-family: \'Microsoft YaHei\'; }')
print('-         [data-testid="stSidebar"] { background-color: #fff; border-right: 1px solid #e5e5e5; }')
print('-         div[data-testid="stMetric"] { background: #fff; border-radius: 10px; padding: 15px; border-left: 4px solid #ff7eb3; box-shadow: 0 2px 6px rgba(0,0,0,0.05); }')
print('-         div.stButton > button { background: #ff7eb3; color: white !important; border: none; font-weight: bold; border-radius: 8px; }')
print('-     </style>')
print('-     """, unsafe_allow_html=True)')
print('+     # 页面样式已在theme_tiktok.css中定义')
print()
print('     # 主页面布局')
print('```')

# 简短说明
print("### 简短说明")
print("- 删除了`render_dashboard`函数中强制设置白色背景的CSS代码，包括：")
print("  - `.stApp { background-color: #f7f7f9; }`")
print("  - `[data-testid=\"stSidebar\"] { background-color: #fff; }`")
print("  - 其他覆盖主题样式的规则")
print("- 确保应用程序现在使用`.streamlit/config.toml`中定义的深色主题和`assets/theme_tiktok.css`中定义的抖音风格样式")
print("- 所有文字现在将使用浅色字体，在深色背景下清晰可读")
